### ISSUE TITLE
Authorization not working

### ISSUE THREAD

**Issue by erickmedrado** [mpcowan/trello-insights#14]
I installed the power up on my Trello board, but when i click on the button "Authorize Access To Trello" nothing happens.
The authorization is visible on my account settings, but when i click on Insights button in my Board a authorization screen appears again. 

This error apear on Google DevTools when i click on Insights button:

`Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag.   jquery.js:6333`

**Comment by mpcowan** [comment]
@erickmedrado Thanks for reporting. The issue appeared to be that Trello changed the format of their authorization tokens and the Power-Up wasn't set to handle that. I've deployed a fix so it should be working again.
